version: '3.8'

services:
  pendientes-app:
    build: .
    image: pendientes-bei:latest
    container_name: pendientes-bei-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # Persistencia de datos: Mapeamos el archivo db.json local al del contenedor
      # Asegúrate de crear un archivo db.json vacío o con datos iniciales en tu NAS si no existe
      - ./backend/db.json:/app/backend/db.json
    environment:
      - PORT=3000
      - SECRET_KEY=cambia_esto_por_una_clave_segura_en_tu_nas
      - ADMIN_PASSWORD=admin123
