version: '3'
services:
  pendientes-app:
    build: .
    container_name: pendientes-bei-app
    restart: always
    user: root
    ports:
      - "3017:3017"
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production
      - PORT=3017
