version: '3'
services:
  pendientes-app:
    build: .
    container_name: pendientes-bei-app
    restart: always
    user: root
    network_mode: host
    volumes:
      - ./frontend-react:/app/frontend-react
    environment:
      - NODE_ENV=production
      - PORT=3001
