version: '3'
services:
  pendientes-app:
    build: .
    container_name: pendientes-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./db.json:/app/db.json
      - ./public/images:/app/public/images
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production
